//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturas {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\sunat_archivos\\sfs\\DATA\\")]
        public string DirectorioDATA {
            get {
                return ((string)(this["DirectorioDATA"]));
            }
            set {
                this["DirectorioDATA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\sunat_archivos\\sfs\\FIRMA\\")]
        public string DirectorioFIRMA {
            get {
                return ((string)(this["DirectorioFIRMA"]));
            }
            set {
                this["DirectorioFIRMA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\sunat_archivos\\sfs\\IMG\\")]
        public string DirectorioIMG {
            get {
                return ((string)(this["DirectorioIMG"]));
            }
            set {
                this["DirectorioIMG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\sunat_archivos\\sfs\\REPO\\")]
        public string DirectorioREPO {
            get {
                return ((string)(this["DirectorioREPO"]));
            }
            set {
                this["DirectorioREPO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\sunat_archivos\\sfs\\RPTA\\")]
        public string DirectorioRPTA {
            get {
                return ((string)(this["DirectorioRPTA"]));
            }
            set {
                this["DirectorioRPTA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\DESKTOP-KQB7347\\SFS_v1.3.2")]
        public string RutaDirectorio {
            get {
                return ((string)(this["RutaDirectorio"]));
            }
            set {
                this["RutaDirectorio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:9000")]
        public string httpBandeja {
            get {
                return ((string)(this["httpBandeja"]));
            }
            set {
                this["httpBandeja"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/api/GenerarComprobante.htm")]
        public string httpFirma {
            get {
                return ((string)(this["httpFirma"]));
            }
            set {
                this["httpFirma"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/api/enviarXML.htm")]
        public string httpEnvio {
            get {
                return ((string)(this["httpEnvio"]));
            }
            set {
                this["httpEnvio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/api/ActualizarPantalla.htm")]
        public string httpActualizar {
            get {
                return ((string)(this["httpActualizar"]));
            }
            set {
                this["httpActualizar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/api/MostrarXml.htm")]
        public string httpPdf {
            get {
                return ((string)(this["httpPdf"]));
            }
            set {
                this["httpPdf"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\sunat_archivos\\sfs\\LOG\\")]
        public string RutaLOG {
            get {
                return ((string)(this["RutaLOG"]));
            }
            set {
                this["RutaLOG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data source = WIN-N0KOJNSL9KV; initial catalog = SEGURIMAX02; user id = sa; passw" +
            "ord = Dv123456789")]
        public string CadeCone {
            get {
                return ((string)(this["CadeCone"]));
            }
            set {
                this["CadeCone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\DESKTOP-KQB7347\\SFS_1.3.4.2_GR")]
        public string RutaDirectorioGR {
            get {
                return ((string)(this["RutaDirectorioGR"]));
            }
            set {
                this["RutaDirectorioGR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:9001")]
        public string httpBandeja_GR {
            get {
                return ((string)(this["httpBandeja_GR"]));
            }
            set {
                this["httpBandeja_GR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<!DOCTYPE html>\r\n\r\n<html lang=\"en\" xmlns=\"http://www.w3.org/1999/xhtml\">\r\n<head>\r" +
            "\n    <meta charset=\"utf-8\" />\r\n    <title></title>\r\n</head>\r\n<body>\r\n    <div id" +
            "=\":u8\" class=\"ii gt\">\r\n        <div id=\":u7\" class=\"a3s aXjCH \">\r\n            <d" +
            "iv>\r\n                <div>\r\n                    <table align=\"center\" bgcolor=\"#" +
            "ffffff\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"font-family:Helvetica " +
            "neue,Helvetica,Arial,Verdana,sans-serif\" width=\"100%\">\r\n                        " +
            "<tr>\r\n                            <td colspan=\"1\" rowspan=\"1\">\r\n                " +
            "                <table align=\"center\" bgcolor=\"#ffffff\" border=\"0\" cellpadding=\"" +
            "0\" cellspacing=\"0\" width=\"520px\">\r\n                                    <tr>\r\n   " +
            "                                     <td colspan=\"1\" rowspan=\"1\" valign=\"top\">\r\n" +
            "                                            <table bgcolor=\"#ffffff\" border=\"0\" " +
            "cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n                                 " +
            "               <tr>\r\n                                                    <td ali" +
            "gn=\"left\" colspan=\"1\" rowspan=\"1\" style=\"color:#05AFF2; font-size:20px;line-heig" +
            "ht:32px;text-align:left;font-weight:bold\" valign=\"top\"><span>@DocType @SerNumCor" +
            "</span></td>\r\n                                                </tr>\r\n           " +
            "                                     <tr>\r\n                                     " +
            "               <td colspan=\"1\" rowspan=\"1\" style=\"color:#cccccc;padding-bottom:1" +
            "5px\" valign=\"top\">\r\n                                                        <hr " +
            "color=\"#cccccc\" size=\"1\" />\r\n                                                   " +
            " </td>\r\n                                                </tr>\r\n                 " +
            "                               <tr align=\"left\" colspan=\"1\" rowspan=\"1\" valign=\"" +
            "top\">\r\n                                                    <td>\r\n               " +
            "                                         <div style=\"padding:10px 0; background-" +
            "color: #40454C; color: #DBD7D2;\">\r\n                                             " +
            "               Estimados @NomSocNeg </div>\r\n                                    " +
            "                </td>\r\n                                                </tr>\r\n  " +
            "                                              <tr align=\"left\" colspan=\"1\" rowsp" +
            "an=\"1\" valign=\"top\">\r\n                                                    <td>\r\n" +
            "                                                        <div style=\"padding:10px" +
            " 0; color: #40454C;\">\r\n                                                         " +
            "   Se adjunta en este mensaje una @DocType\r\n                                    " +
            "                    </div>\r\n                                                    " +
            "</td>\r\n                                                </tr>\r\n                  " +
            "                              <tr align=\"left\" colspan=\"1\" rowspan=\"1\" valign=\"t" +
            "op\">\r\n                                                    <td>\r\n                " +
            "                                        <div style=\"padding:5px 0\">\r\n           " +
            "                                                 <ul>\r\n                         " +
            "                                       <li><b>@DocType @SerNumCor </b></li>\r\n   " +
            "                                                             <li>Fecha de emisió" +
            "n: <b>@FecEmi</b></li>\r\n                                                        " +
            "        <li>Total: <b>S/ @TotDoc</b></li>\r\n                                     " +
            "                       </ul>\r\n                                                  " +
            "      </div>\r\n                                                        <div style" +
            "=\"padding:5px 0; color: #40454C;\">\r\n                                            " +
            "                Se adjunta en este mensaje el documento electrónico en formatos " +
            "PDF y XML. La representación impresa en PDF tiene la misma validez que una emiti" +
            "da de manera tradicional.                                    </div>\r\n           " +
            "                                             <div style=\"padding:5px 0; backgrou" +
            "nd-color: #F4B80E; color: #40454C;\">\r\n                                          " +
            "                  Representación impresa de la @DocType generada desde el sistem" +
            "a facturador SUNAT. Puede verificarla utilizando su clave SOL<br />\r\n           " +
            "                                                 <br />\r\n                       " +
            "                                     <a href=\"https://e-consulta.sunat.gob.pe/ol" +
            "-ti-itconsvalicpe/ConsValiCpe.htm\">https://e-consulta.sunat.gob.pe/ol-ti-itconsv" +
            "alicpe/ConsValiCpe.htm</a></div>\r\n                                              " +
            "      </td>\r\n                                                </tr>\r\n            " +
            "                                    <tr align=\"left\" colspan=\"1\" rowspan=\"1\" val" +
            "ign=\"top\">\r\n                                                    <td>\r\n          " +
            "                                              <div>\r\n                           " +
            "                                 <table bgcolor=\"#ffffff\" border=\"0\" cellpadding" +
            "=\"0\" cellspacing=\"0\" width=\"100%\">\r\n                                            " +
            "                    <tr valign=\"top\">\r\n                                         " +
            "                           <td align=\"left\" colspan=\"1\" rowspan=\"1\" style=\"paddi" +
            "ng-top:10px;text-align:left; color: #40454C;\" valign=\"top\"><span>Atentamente</sp" +
            "an>:<br clear=\"none\" />\r\n                                                       " +
            "                 @RazSoc<br clear=\"none\" />\r\n                                   " +
            "                                     <span><b>RUC @Ruc</b></span><br clear=\"none" +
            "\" />\r\n                                                                        <b" +
            "r />\r\n                                                                    </td>\r" +
            "\n                                                                </tr>\r\n        " +
            "                                                    </table>\r\n                  " +
            "                                      </div>\r\n                                  " +
            "                  </td>\r\n                                                </tr>\r\n" +
            "                                                <tr>\r\n                          " +
            "                          <td colspan=\"1\" rowspan=\"1\">\r\n                        " +
            "                                <table align=\"center\" bgcolor=\"#ffffff\" border=\"" +
            "0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n                              " +
            "                              <tr>\r\n                                            " +
            "                    <td colspan=\"1\" rowspan=\"1\" style=\"color:#DBD7D2; text-align" +
            ": center; font-size: xx-small; background-color: #40454C;\" valign=\"top\" width=\"1" +
            "00%\">\r\n                                                                    TgrSy" +
            "stem<br />\r\n                                                                    " +
            "51-993433774</td>\r\n                                                            <" +
            "/tr>\r\n                                                            <tr>\r\n        " +
            "                                                        <td colspan=\"1\" rowspan=" +
            "\"1\">\r\n                                                                    <div>\r" +
            "\n                                                                        <table " +
            "align=\"center\" bgcolor=\"#ffffff\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" widt" +
            "h=\"100%\">\r\n                                                                     " +
            "       <tr>\r\n                                                                   " +
            "             <td align=\"left\" colspan=\"1\" rowspan=\"1\" style=\"padding-top:10px;co" +
            "lor:#707070;font-size:12px;line-height:14px;text-align:left\" valign=\"top\">\r\n    " +
            "                                                                                " +
            "<br clear=\"none\" />\r\n                                                           " +
            "                     </td>\r\n                                                    " +
            "                        </tr>\r\n                                                 " +
            "                       </table>\r\n                                               " +
            "                     </div>\r\n                                                   " +
            "             </td>\r\n                                                            " +
            "</tr>\r\n                                                        </table>\r\n       " +
            "                                             </td>\r\n                            " +
            "                    </tr>\r\n                                            </table>\r" +
            "\n                                        </td>\r\n                                " +
            "    </tr>\r\n                                </table>\r\n                           " +
            " </td>\r\n                        </tr>\r\n                    </table>\r\n           " +
            "         <div class=\"yj6qo\">\r\n                    </div>\r\n                    <d" +
            "iv class=\"adL\">\r\n                    </div>\r\n                </div>\r\n           " +
            "     <div class=\"adL\">\r\n                </div>\r\n                <div class=\"adL\"" +
            ">\r\n                </div>\r\n                <div class=\"adL\">\r\n                </" +
            "div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <div id=\":uz\" class=\"h" +
            "q gt\">\r\n        <div class=\"hp\">\r\n        </div>\r\n    </div>\r\n</body>\r\n</html>\r\n" +
            "")]
        public string CuerpoCorreo {
            get {
                return ((string)(this["CuerpoCorreo"]));
            }
            set {
                this["CuerpoCorreo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("smtp.live.com")]
        public string ServidorSMTP {
            get {
                return ((string)(this["ServidorSMTP"]));
            }
            set {
                this["ServidorSMTP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("segurimax_80@hotmail.com")]
        public string UsuarioSMTP {
            get {
                return ((string)(this["UsuarioSMTP"]));
            }
            set {
                this["UsuarioSMTP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int PuertoSMTP {
            get {
                return ((int)(this["PuertoSMTP"]));
            }
            set {
                this["PuertoSMTP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("j21np33l")]
        public string PassUsuaSMTP {
            get {
                return ((string)(this["PassUsuaSMTP"]));
            }
            set {
                this["PassUsuaSMTP"] = value;
            }
        }
    }
}
